### PR TITLE
Use scrollIntoView to scroll on anchor links

### LINKED ISSUE #85: Change window.location.hash; and test in web browsers
_Originally posted by @srid in https://github.com/srid/ema/pull/83#discussion_r807496211_

### PR DESCRIPTION
**Pull request by srid**
Builds on top of #83, and resolves #85 

Works on Chrome and Safari (Safari doesn't support smooth scrolling however).

### CODE REVIEW

**Comment by srid** [comment]
@lucasvreis I don't have Firefox, so haven't tested this on it.

**Comment by lucasvreis** [comment]
Works fine on Firefox. One perhaps undesirable behavior (not related to this change or Firefox) is that it scrolls to the anchor in every DOM patch, and this can be annoying or surprising if you are editing the page. I think it works better if after a `switchRoute` call the client only scrolls to anchor once:
```patch
 src/Ema/Server.hs | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/src/Ema/Server.hs b/src/Ema/Server.hs
index cb98105..882f188 100644
--- a/src/Ema/Server.hs
+++ b/src/Ema/Server.hs
@@ -278,6 +278,8 @@ wsClientShim =
         function init(reconnecting) {
           // The route current DOM is displaying
           let routeVisible = document.location.pathname;
+          // If client should scroll to anchor on next DOM patch
+          let pendingHashChange = false;
 
           const verb = reconnecting ? "Reopening" : "Opening";
           console.log(`ema: $${verb} conn $${wsUrl} ...`);
@@ -300,6 +302,7 @@ wsClientShim =
           function switchRoute(path, hash = "") {
              console.log(`ema: → Switching to $${path + hash}`);
              window.history.pushState({}, "", path + hash);
+             if (hash) { pendingHashChange = true };
              sendObservePath(path);
           }
 
@@ -358,11 +361,12 @@ wsClientShim =
                 window.scrollTo({ top: 0});
                 routeVisible = document.location.pathname;
               }
-              if (window.location.hash) {
+              if (pendingHashChange && window.location.hash) {
                 var el = document.querySelector(window.location.hash);
                 if (el !== null) {
                   el.scrollIntoView({ behavior: 'smooth' });
                 }
+                pendingHashChange = false;
               }
               watchCurrentRoute();
             };
-- 
2.35.1
```
Do you agree / should I open a PR?

**Comment by srid** [comment]
> Do you agree / should I open a PR?

Yup.

> `if (hash) { pendingHashChange = true };`

What about the reverse direction? ie., you were viewing `/foo#hash`, and then switched to `/foo`. I guess I have to try this out in https://github.com/srid/ema-template ...

**Comment by lucasvreis** [comment]
@srid Seems to work as expected:
Peek 18-02-2022 14-55

**Pull request merged**
