### PR TITLE
Filter unit types and derive HasSubModels generically

### PR DESCRIPTION
**Pull request by lucasvreis**
See: https://github.com/srid/ema/pull/93#issuecomment-1168165703

Made this PR so you can edit/merge the changes if you like.

### CODE REVIEW

**Comment by srid** [comment]
Thanks!

I hadn't thought of using lens for subModels. `subModelsLens` looks like a good idea. 

It looks like you are using `FilterNonUnit` (5e1ed91) to strip down the model so that `productTypeFrom` can be used (but see next paragraph). I cannot yet understand why we need `FilterNonUnit`.

I think there is a bug in the generic deriving of HasSubModels (b5bea4b). It can only work if your model is equivalent to (not superset of) the set of sub-models, AFAIU. For example, if you add another field to the model type in Ex03_Store.hs, 

```haskell
data Model = Model
  { modelProducts :: [Product]
  , modelCategories :: [Category]
  , mFoo :: Int -- Extra field, irrelevant to route encoders
  }
```

it will throw an error:

```haskell
src/Ema/Example/Ex03_Store.hs:46:13-24: error:
    • Couldn't match type: (':) @Type Int ('[] @Type)
                     with: '[] @Type
        arising from the 'deriving' clause of a data type declaration
    • When deriving the instance for (HasSubModels Route)
   |
46 |   deriving (HasSubModels, IsRoute) via (Route `WithModel` Model)
```

It also assumes that the equivalent model has fields in the same order as routes, which may be problematic in the long-run.

**Comment by lucasvreis** [comment]
The error in this example is intended, because otherwise there could be ambiguity. What should happen if `mFoo` is also of type `[Category]`? We would have to impose some convention, like requiring all the route submodels to come first in the product, or (the way I like better) leave it like this and then build another "route template" `WithSubModel r interface model` on top for models that are subtypes but using records, and the user selects which fields they are interested in by defining the "interface".

**Comment by srid** [comment]
> build another "route template" `WithSubModel r interface model` on top for models that are subtypes but using records, and the user selects which fields they are interested in by defining the "interface".

How would this look like, from user point of view, for Ex03_Store.hs with e950c66800a79b1aad629c764112148da8c977e1 ?

**Comment by srid** [comment]
Perhaps we can make `subModels` return a `NP` *of* `Lens'`. 

```haskell
subModels :: RouteModel r -> NP (Lens' (RouteModel r)) (MultiModel (SubRoutes r))
```

**Comment by srid** [comment]
Uh, deleting the branch automatically closed this. 

@lucasvreis Sorry this PR didn't make it, but I remain interested in your ideas and/or prototypes regarding the sub-model part of the API. It seems like that, along with `deviveIsRoute` TH, would be the main thing to do before 0.8 release.

(I tried to remove/refactor the hacky `NPConst` thing using your `FilterNonUnit` but couldn't succeed ...)

**Pull request closed without merging**
